### ISSUE TITLE
Make it easier to use many scenes

### ISSUE THREAD

**Issue by shelvick** [defun-games/claylib#17]
We're using multiple scenes in core example 2, but not to great effect.

The crux of the issue is that you want to switch scenes within your game, i.e. within a `do-game-loop`. Yet `do-game-loop` is... well, a loop, and `with-scene` is not set up to work very well in a loop, with the loading it does, etc. It's easy to get around this in simple examples by just using one scene and putting it outside of the loop, but this won't work for real-world games.

The way forward might be to add a `:scene` keyword to `do-game-loop` and have it do some of the work that `with-scene` currently does whenever the scene changes. Then changing the scene within that loop is just a matter of `(setf scene 'whatever)`.

**Comment by mjkalyan** [comment]
For a case like core example 2 it would make sense to have a `make-scenes` (plural) macro. But that doesn't always work because you may not want to load everything up front.

Switching a scene entails:
1) loading assets when necessary
2) initializing objects when necessary
3) doing memory cleanup for the old scene according to the same logic as `with-scene`

So to be clear the idea is that `do-game-loop` takes a starting `:scene` which we can change by `setf`ing `scene` and on each loop iteration we'd check whether `scene` has changed then perform the above steps?

**Comment by shelvick** [comment]
I've pushed a new version of core example 2 that's a bit cleaner and does use `with-scene` in the game loop. Works fine for that example but I'm still concerned it may break down in a larger game.

> For a case like core example 2 it would make sense to have a `make-scenes` (plural) macro.

Main problem is then with how we're doing it now, you're combining the namespaces of multiple scenes. Not that that's hard to work around, but users may not realize they'd _have_ to work around it.

> So to be clear the idea is that `do-game-loop` takes a starting `:scene` which we can change by `setf`ing `scene` and on each loop iteration we'd check whether `scene` has changed then perform the above steps?

Exactly. We'd probably use a special variable for that (`*scene*`) but you get the idea.

Come to think of it... you're going to have games where it's okay and expected to pause between scenes -- very different scenes with lots of loading involved. But you're also going to have games where the scenes have a lot more overlap, and a loading pause would be jarring. So maybe we do offer a `with-scenes` after all, for those latter cases.

**Comment by mjkalyan** [comment]
Yeah I wasn't that clear but I was imagining we'd have both. That way we prevent ugly nested `with-scene`s when we need a lot of scenes available at once, but still get scene switching where needed inside `do-game-loop`.

Also maybe `do-game-loop`'s `:scene` variable should be a list (`:scenes`) instead for switching between sets of scenes. This wouldn't be hard as soon as the logic for the set-up/tear-down of multiple scenes is in place (from `with-scenes`). The combination of the above would give us the ability to do something like this:
```lisp
(defvar *p1-board* (make-scene ...))
(defvar *p2-board* (make-scene ...))
(defvar *p3-board* (make-scene ...))
(defvar *backdrop-simple* (make-scene ...))
(defvar *backdrop-fancy* (make-scene ...))

(defparameter *current-match* (list *p1-board* *p2-board*))

(with-scenes (list *backdrop-simple* *backdrop-fancy*) ()
  ;; Do some initial stuff with the backdrops here
  (do-game-loop (:scenes *current-match*)
    ;; ...
    (when first-match-over
      (setf *current-match* (list *p1-board* *p3-board*)
            *scenes* *current-match*))
    ;; ...
    ))
```
A bit contrived but it might happen sometimes. Most of the time I imagine you won't need `with-scene`/`with-scenes` because most initialization logic would probably happen in your `make-scene`s and `do-game-loop` should handle the scene set-up/tear-down.

**Comment by mjkalyan** [comment]
Closed by #18

Use multiple scenes with `(with-scenes list-of-scenes)` or, for more manual control, use `set-up-scene`/`tear-down-scene`.
